on: [pull_request]
jobs:
  get-folders:
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.save-variable.outputs.PATHS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout branch 'main'
        uses: actions/checkout@v4
        with:
          ref: main
          path: tmp/

      - id: changed-folders
        name: Get changed directories
        uses: tj-actions/changed-files@v35.6.1
        with:
          dir_names: true
          files: environments/**
          json: true

      - id: save-variable
        run: |
          echo PATHS=${{ steps.changed-folders.outputs.all_modified_files }} | tee -a $GITHUB_OUTPUT
  infracost:
    runs-on: ubuntu-latest
    needs: get-folders
    permissions:
      contents: read
      # Required to post comments
      pull-requests: write
    strategy:
      fail-fast: false
      max-parallel: 30
      matrix:
        folder: ${{fromJson(needs.get-folders.outputs.folders)}}

    steps:
      - name: Print folders
        run: echo ${{ matrix.folder }}

      - name: Replace slashes with dashes
        id: replace-slashes
        run: |
          echo folder_name=$(echo "${{ matrix.folder }}" | awk '{gsub("/", "-"); print}') | tee -a $GITHUB_OUTPUT

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        # See https://github.com/infracost/actions/tree/master/setup for other inputs
        # If you can't use this action, see Docker images in https://infracost.io/cicd
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Checkout branch 'main'
        uses: actions/checkout@v4
        with:
          ref: main
          path: tmp/

      #Print /tmp
      - name: Print tmp
        run: ls -la tmp

      - name: Checkout branch 'PR'
        uses: actions/checkout@v4

      # Generate Infracost JSON file as the baseline.
      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=tmp/${{ matrix.folder }} \
            --format=json \
            --out-file=/tmp/infracost-base-${{steps.replace-slashes.outputs.folder_name}}.json

      #Print /tmp/infracost-base-${{steps.replace-slashes.outputs.folder_name}}.json
      - name: Print /tmp/infracost-base-${{steps.replace-slashes.outputs.folder_name}}.json
        run: cat /tmp/infracost-base-${{steps.replace-slashes.outputs.folder_name}}.json

      # Generate an Infracost diff and save it to a JSON file.
      - name: Generate Infracost diff
        run: |
          infracost diff --path=${{ matrix.folder }} \
            --format=json \
            --compare-to=/tmp/infracost-base-${{steps.replace-slashes.outputs.folder_name}}.json \
            --out-file=/tmp/infracost-${{steps.replace-slashes.outputs.folder_name}}.json

      # Print /tmp/infracost-${{steps.replace-slashes.outputs.folder_name}}.json
      - name: Print /tmp/infracost-${{steps.replace-slashes.outputs.folder_name}}.json
        run: cat /tmp/infracost-${{steps.replace-slashes.outputs.folder_name}}.json
      # Posts a comment to the PR using the 'update' behavior.
      # This creates a single comment and updates it. The "quietest" option.
      # The other valid behaviors are:
      #   delete-and-new - Delete previous comments and create a new one.
      #   hide-and-new - Minimize previous comments and create a new one.
      #   new - Create a new cost estimate comment on every push.
      # See https://www.infracost.io/docs/features/cli_commands/#comment-on-pull-requests for other options.
      - name: Post Infracost comment
        run: |
          infracost comment github --path=/tmp/infracost-${{steps.replace-slashes.outputs.folder_name}}.json \
                                   --repo=$GITHUB_REPOSITORY \
                                   --github-token=${{github.token}} \
                                   --pull-request=${{github.event.pull_request.number}} \
                                   --behavior=new
